Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.disksize.size = '40GB'

    config.vm.define :ueransim, autostart: false do |ueransim|
        ueransim.vm.hostname = 'ue-ran-sim'
        ueransim.vm.network "private_network", ip: "192.168.56.3", nic_type: "82540EM"
        ueransim.vm.network "private_network", ip: "192.168.56.4", nic_type: "82540EM"

        ueransim.vm.provider "virtualbox" do |vb|
            vb.name = "ueransim"
            vb.memory = "1024"
            vb.cpus = 1
        end
    end
end